### ISSUE TITLE
Discussion regarding the Annex of RFC 16

### ISSUE THREAD

**Issue by NZT48** [OriginTrail/OT-RFC-repository#39]
Hi Tracers,

We're excited to share updates to RFC 16, focusing on bridges implementation for the OriginTrail Parachain. These updates provide latest information about Phase 1 and Phase 2 of the parachain bridges.

You can review the changes and gain more information by accessing the updated RFC through this [link](https://github.com/OriginTrail/OT-RFC-repository/blob/main/RFCs/OT-RFC-16-Parachain-Bridges-Implementation/OT-RFC-16-Parachain-Bridges-Implementation.pdf). Additionally, we welcome your feedback and comments on the proposal, which you can provide by opening a PR or reviewing the [markdown file](https://github.com/OriginTrail/OT-RFC-repository/blob/main/RFCs/OT-RFC-16-Parachain-Bridges-Implementation/README.md).

As always your feedback and comments are much appreciated.

Trace on!

**Comment by Valcyclovir** [comment]
Hello @NZT48,

In regards to the update on getting TRAC and OTP on Moonbeam using xcm transfer, I noticed that you could get xcTRAC bridged using Wormhole back to Ethereum blockchain without having to go through a DEX to swap xcTRAC <-> moonbeamTRAC. I can bridge my xcTRAC through Wormhole right away. Wouldn't that go against the approach agreed on ? If another hack were to happen on Wormhole, that would directly affect xcTRAC, and not a "bridged intermediary" TRAC as agreed upon. 

Are there any plans to instate a DEX for moonbeamTRAC <-> xcTRAC ?

![Screenshot_20231015_235733](https://github.com/OriginTrail/OT-RFC-repository/assets/85747941/17ac03f3-2e09-4122-97f2-0acc3cc72e93)

**Comment by Valcyclovir** [comment]
Context: 
The introduction of Moonbeam TRAC and xcOTP as per RFC-16 has been going smoothly. The Wormhole bridge to bridge ERC-20 TRAC to moonbeamTRAC is live and working, and the xcOTP <-> moonbeamTRAC pair on Stellaswap seems to be working as well. As per the RFC, xcTRAC is well protected from moonbeamTRAC risks.

Issue:
OTP can now be xcm transfered to moonbeam and be traded against moonbeamTRAC. In the event that moonbeamTRAC suffers an attack, the xcOTP <-> moonbeamTRAC pool will become compromised. 

Objective: 
- The collateral damage in case of a bridge hack should be minimized;
- Proposed solution must not add complexity to the end user;
- Proposed solution must be easy to implement.

Suggestion:
Implement a xcOTP <-> xcTRAC pool instead of the current xcOTP <-> moonbeamTRAC pool. MoonbeamTRAC should only have 1 vector of attack rather than 2. The end user who bridges ERC-20 TRAC to moonbeam through Wormhole (or any other 3rd party bridge) can trade moonbeamTRAC for xcTRAC, and then exchange xcTRAC for some xcOTP. The number of steps for the end user remain the same, as the user would need to trade moonbeamTRAC for xcOTP and xcTRAC in any case. If moonbeamTRAC gets compromised, only 1 pool will be affected instead of both moonbeamTRAC <-> xcTRAC and moonbeamTRAC <-> xcOTP. The proposed solution is to implement a xcOTP <-> xcTRAC pool rather than the current xcOTP <-> moonbeamTRAC pool, and to keep moonbeamTRAC as isolated as possible, only allowing it to be exchanged against xcTRAC in order to mitigate risks.
